// Generated by CoffeeScript 1.6.3
(function() {
  var data, file, finalData, fs, unprocessedData, _;

  console.log("Archivo a procesar: " + process.argv[2]);

  fs = require("fs");

  _ = require('underscore')._;

  file = __dirname + ("/" + process.argv[2]);

  unprocessedData = null;

  data = {};

  finalData = [];

  fs.readFile(file, "utf8", function(err, readData) {
    var anio, criterio, criterios, cultivo, cultivos, outFileName, departamento, departamentos, row, valor, variedad, variedades;
    if (err) {
      console.log("Error: " + err);
      return;
    }
    unprocessedData = JSON.parse(readData);
    _.each(unprocessedData, function(row) {
      if (!data[row.anio]) {
        data[row.anio] = {};
      }
      if (!data[row.anio][row.departamento]) {
        data[row.anio][row.departamento] = {};
      }
      if (!data[row.anio][row.departamento][row.cultivo]) {
        data[row.anio][row.departamento][row.cultivo] = {};
      }
      if (!data[row.anio][row.departamento][row.cultivo][row.variedad]) {
        data[row.anio][row.departamento][row.cultivo][row.variedad] = {};
      }
      return data[row.anio][row.departamento][row.cultivo][row.variedad][row.criterio] = row.valor;
    });
    for (anio in data) {
      departamentos = data[anio];
      for (departamento in departamentos) {
        cultivos = departamentos[departamento];
        for (cultivo in cultivos) {
          variedades = cultivos[cultivo];
          for (variedad in variedades) {
            criterios = variedades[variedad];
            row = {
              anio: parseInt(anio),
              departamento: departamento,
              cultivo: cultivo,
              variedad: variedad
            };
            for (criterio in criterios) {
              valor = criterios[criterio];
              row[criterio.toLowerCase()] = valor;
            }
            finalData.push(row);
          }
        }
      }
    }
    console.log("Procesando " + finalData.length + " registros");
    outFileName = "processed-" + process.argv[2];
    return fs.writeFile(outFileName, JSON.stringify(finalData, null, 2), function(err) {
      if (err) {
        return console.log(err);
      } else {
        return console.log("Data procesada: " + outFileName);
      }
    });
  });

}).call(this);
