// Generated by CoffeeScript 1.6.3
(function() {
  var By, DEVEL, criterios, cultivoStr, cultivos, dataFile, dataFileName, driver, endpoint, fs, getAllData, getRow, moment, departamentos, root, urlCount, webdriver, _;

  DEVEL = false;

  fs = require('fs');

  webdriver = require("webdriver-sync");

  By = webdriver.By;

  _ = require('underscore')._;

  moment = require('moment');

  driver = new webdriver.ChromeDriver;

  root = "Siembras";

  cultivoStr = function(categoria, variedad) {
    return "" + root + "," + categoria + "," + variedad;
  };

  endpoint = function(departamento, cultivo, variedad, criterio) {
    var baseUrl, period;
    departamento = "" + root + ",Per%C3%BA," + departamento;
    cultivo = cultivoStr(cultivo, variedad);
    criterio = "" + root + "," + criterio;
    period = '';
    _([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013]).each(function(year) {
      return period += "" + root + "," + year + ";";
    });
    period = period.slice(0, -1);
    baseUrl = "http://agroaldia.minag.gob.pe/sisin/clients/detalle/";
    if (!DEVEL) {
      return "" + baseUrl + "location:" + departamento + "/subject:" + criterio + "/domain:" + cultivo + "/period:" + period + "/axis:/flatten:1/prefix:" + root + "/write:1/bc:";
    }
    return "file:///home/merunga/escuelab/agro-peru/scraper/static.html";
  };

  departamentos = ["Amazonas", "Ancash", "Apurímac", "Arequipa", "Ayacucho", "Cajamarca", "Cusco", "Huancavelica", "Huánuco", "Ica", "Junín", "La Libertad", "Lambayeque", "Lima", "Loreto", "Madre de Dios", "Moquegua", "Pasco", "Piura", "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali"];

  cultivos = [
    {
      categoria: "Ajo",
      variedades: ["Ajo"]
    }, {
      categoria: "Algodón",
      variedades: ["Algodón Rama"]
    }, {
      categoria: "Arroz",
      variedades: ["Arroz Cascara"]
    }, {
      categoria: "Cacao",
      variedades: ["Cacao"]
    }, {
      categoria: "Café",
      variedades: ["Café"]
    }, {
      categoria: "Caña de Azúcar",
      variedades: ["Caña de Azúcar"]
    }, {
      categoria: "Cebolla",
      variedades: ["Cebolla"]
    }, {
      categoria: "Limón",
      variedades: ["Limón"]
    }, {
      categoria: "Mandarina y Tangelo",
      variedades: ["Mandarina y Tangelo"]
    }, {
      categoria: "Naranja",
      variedades: ["Naranja"]
    }, {
      categoria: "Espárrago",
      variedades: ["Espárrago"]
    }, {
      categoria: "Maíz Amarillo Duro",
      variedades: ["Maíz Amarillo Duro"]
    }, {
      categoria: "Maíz Amilaceo",
      variedades: ["Maíz Amilaceo", "Maíz Choclo"]
    }, {
      categoria: "Mango",
      variedades: ["Mango"]
    }, {
      categoria: "Arverja",
      variedades: ["Arverja Grano Seco", "Arverja Grano Verde"]
    }, {
      categoria: "Frijol",
      variedades: ["Frijol Castilla", "Frijol de Palo", "Frijol Grano Seco", "Frijol Loctao", "Frijol"]
    }, {
      categoria: "Lenteja",
      variedades: ["Lenteja"]
    }, {
      categoria: "Olivo",
      variedades: ["Aceituna"]
    }, {
      categoria: "Palma Aceitera",
      variedades: ["Palma Aceitera"]
    }, {
      categoria: "Palta",
      variedades: ["Palta"]
    }, {
      categoria: "Papa",
      variedades: ["Papa"]
    }, {
      categoria: "Platano",
      variedades: ["Platano"]
    }, {
      categoria: "Quinua",
      variedades: ["Quinua"]
    }, {
      categoria: "Sorgo",
      variedades: ["Sorgo"]
    }, {
      categoria: "Soya",
      variedades: ["Soya"]
    }, {
      categoria: "Trigo",
      variedades: ["Trigo"]
    }, {
      categoria: "Vid",
      variedades: ["Uva"]
    }, {
      categoria: "Yuca",
      variedades: ["Yuca"]
    }
  ];

  criterios = ["Cosecha", "Produccion", "Rendimiento", "Precio"];

  dataFileName = "data/data-" + (moment().format('YYYY-MM-DD-HH-mm')) + ".json";

  console.log("Data file: " + dataFileName + "\n");

  dataFile = fs.openSync(dataFileName, "w");

  urlCount = 0;

  getRow = function(departamento, cultivo, variedad, criterio) {
    var e, url,
      _this = this;
    if (departamento == null) {
      departamento = "Amazonas";
    }
    if (cultivo == null) {
      cultivo = "Ajo";
    }
    if (variedad == null) {
      variedad = "Ajo";
    }
    if (criterio == null) {
      criterio = "Produccion";
    }
    url = endpoint(departamento, cultivo, variedad, criterio);
    urlCount++;
    console.log("[" + (moment().format('YYYY-MM-DD HH:mm:ss')) + "] begin GET: " + url);
    driver.get(url);
    try {
      driver.findElement(By.id("ToolTables_0_4")).click();
      _(driver.findElements(By.xpath('//table[@class="display"]//tr'))).each(function(tr) {
        var hayData, row;
        row = {
          "cultivo": cultivo,
          "variedad": variedad,
          "criterio": criterio,
          "departamento": departamento
        };
        hayData = false;
        _(tr.findElements(By.tagName('td'))).each(function(td, idx) {
          var text;
          hayData = true;
          text = td.getText();
          switch (idx) {
            case 1:
              return row["anio"] = parseInt(text);
            case 3:
              return row["valor"] = parseFloat(text);
          }
        });
        if (hayData) {
          return fs.writeSync(dataFile, "" + (JSON.stringify(row)) + ",\n");
        }
      });
    } catch (_error) {
      e = _error;
      console.log('** WARNING **: No hay data');
    }
    return console.log("[" + (moment().format('YYYY-MM-DD HH:mm:ss')) + "] end GET " + urlCount + "\n");
  };

  getAllData = function() {
    fs.writeSync(dataFile, "[ \n");
    _.each(cultivos, function(cultivo) {
      return _.each(departamentos, function(departamento) {
        var categoria;
        categoria = cultivo.categoria;
        return _.each(cultivo.variedades, function(variedad) {
          return _.each(criterios, function(criterio) {
            return getRow(departamento, categoria, variedad, criterio);
          });
        });
      });
    });
    return fs.writeSync(dataFile, " ]\n");
  };

  if (DEVEL) {
    getRow();
  } else {
    getAllData();
  }

  driver.quit();

}).call(this);
